{"uuid": "df842e59-7e62-4be9-886f-d0e1788a4c39", "children": ["11a59dfb-3673-4920-b0f2-57540c5d19d6"], "befores": [{"name": "driver", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.WebDriverException: Message: Service /root/.wdm/drivers/chromedriver/linux64/101.0.4951.41/chromedriver unexpectedly exited. Status code was: 127\n\n", "trace": "  File \"/usr/local/lib/python3.8/site-packages/pluggy/_callers.py\", line 39, in _multicall\n    res = hook_impl.function(*args)\n  File \"/usr/local/lib/python3.8/site-packages/_pytest/fixtures.py\", line 1122, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"/usr/local/lib/python3.8/site-packages/_pytest/fixtures.py\", line 917, in call_fixture_func\n    fixture_result = next(generator)\n  File \"/final_project/code/ui_myapp/tools/fixtures.py\", line 26, in driver\n    driver = webdriver.Chrome(executable_path=ChromeDriverManager().install())\n  File \"/usr/local/lib/python3.8/site-packages/selenium/webdriver/chrome/webdriver.py\", line 70, in __init__\n    super(WebDriver, self).__init__(DesiredCapabilities.CHROME['browserName'], \"goog\",\n  File \"/usr/local/lib/python3.8/site-packages/selenium/webdriver/chromium/webdriver.py\", line 90, in __init__\n    self.service.start()\n  File \"/usr/local/lib/python3.8/site-packages/selenium/webdriver/common/service.py\", line 98, in start\n    self.assert_process_still_running()\n  File \"/usr/local/lib/python3.8/site-packages/selenium/webdriver/common/service.py\", line 110, in assert_process_still_running\n    raise WebDriverException(\n"}, "start": 1653175722069, "stop": 1653175722705}], "start": 1653175722069, "stop": 1653175722726}