{"name": "Страница регистрации. Pop-up \"User already exists\" при повторении username", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.WebDriverException: Message: Service /root/.wdm/drivers/chromedriver/linux64/101.0.4951.41/chromedriver unexpectedly exited. Status code was: 127", "trace": "config = {'browser': 'chrome', 'debug_log': False, 'selenoid': None, 'url': 'http://my_app:8086/', ...}\ntemp_dir = '/tmp/tests/code/ui_myapp/tests/test_ui.py::TestUIUnauthorizedUserRegistrationPage::test_reg_page_validation_already_used_user'\n\n    @pytest.fixture()\n    def driver(config, temp_dir):\n        browser = config['browser']\n        url = config['url']\n        selenoid = config['selenoid']\n        vnc = config['vnc']\n        if selenoid:\n            capabilities = {\n                'browserName': 'chrome',\n                'version': '98.0',\n            }\n            if vnc:\n                capabilities['enableVNC'] = True\n            driver = webdriver.Remote(\n                'http://127.0.0.1:4444/wd/hub',\n                desired_capabilities=capabilities\n            )\n        else:\n>           driver = webdriver.Chrome(executable_path=ChromeDriverManager().install())\n\nbrowser    = 'chrome'\nconfig     = {'browser': 'chrome', 'debug_log': False, 'selenoid': None, 'url': 'http://my_app:8086/', ...}\nselenoid   = None\ntemp_dir   = '/tmp/tests/code/ui_myapp/tests/test_ui.py::TestUIUnauthorizedUserRegistrationPage::test_reg_page_validation_already_used_user'\nurl        = 'http://my_app:8086/'\nvnc        = False\n\ncode/ui_myapp/tools/fixtures.py:26: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n/usr/local/lib/python3.8/site-packages/selenium/webdriver/chrome/webdriver.py:70: in __init__\n    super(WebDriver, self).__init__(DesiredCapabilities.CHROME['browserName'], \"goog\",\n        __class__  = <class 'selenium.webdriver.chrome.webdriver.WebDriver'>\n        chrome_options = None\n        desired_capabilities = None\n        executable_path = '/root/.wdm/drivers/chromedriver/linux64/101.0.4951.41/chromedriver'\n        keep_alive = True\n        options    = None\n        port       = 0\n        self       = <[AttributeError(\"'WebDriver' object has no attribute 'session_id'\") raised in repr()] WebDriver object at 0x7fa77a0dd2b0>\n        service    = <selenium.webdriver.chrome.service.Service object at 0x7fa77a0dd910>\n        service_args = None\n        service_log_path = None\n/usr/local/lib/python3.8/site-packages/selenium/webdriver/chromium/webdriver.py:90: in __init__\n    self.service.start()\n        __class__  = <class 'selenium.webdriver.chromium.webdriver.ChromiumDriver'>\n        _ignore_proxy = None\n        browser_name = 'chrome'\n        desired_capabilities = None\n        keep_alive = True\n        options    = <selenium.webdriver.chrome.options.Options object at 0x7fa77a0dd4f0>\n        port       = 0\n        self       = <[AttributeError(\"'WebDriver' object has no attribute 'session_id'\") raised in repr()] WebDriver object at 0x7fa77a0dd2b0>\n        service    = <selenium.webdriver.chrome.service.Service object at 0x7fa77a0dd910>\n        service_args = None\n        service_log_path = None\n        vendor_prefix = 'goog'\n/usr/local/lib/python3.8/site-packages/selenium/webdriver/common/service.py:98: in start\n    self.assert_process_still_running()\n        cmd        = ['/root/.wdm/drivers/chromedriver/linux64/101.0.4951.41/chromedriver', '--port=36111']\n        count      = 1\n        self       = <selenium.webdriver.chrome.service.Service object at 0x7fa77a0dd910>\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nself = <selenium.webdriver.chrome.service.Service object at 0x7fa77a0dd910>\n\n    def assert_process_still_running(self):\n        return_code = self.process.poll()\n        if return_code:\n>           raise WebDriverException(\n                'Service %s unexpectedly exited. Status code was: %s'\n                % (self.path, return_code)\n            )\nE           selenium.common.exceptions.WebDriverException: Message: Service /root/.wdm/drivers/chromedriver/linux64/101.0.4951.41/chromedriver unexpectedly exited. Status code was: 127\n\nreturn_code = 127\nself       = <selenium.webdriver.chrome.service.Service object at 0x7fa77a0dd910>\n\n/usr/local/lib/python3.8/site-packages/selenium/webdriver/common/service.py:110: WebDriverException"}, "description": "\n                                              Тестирование: Регистрация. Username уже добавлен ранее в БД\n                                              Предусловия: Сгенерировать валидные данные, заменить username на\n                                              использованный ранее\n                                              Шаги:\n                                              1. Заполнить через UI все поля регистрации\n                                              Ожидаемый результат:\n                                              1. Пользователь остается на странице /reg (+)\n                                              2. Показывается pop-up, уведомляющий о том, что username уже\n                                              используется (+)\n                                              3. Пользователь с указанными данными не создается в БД (+)\n                                              Фактический результат:\n                                              1. Пользователь остается на странице /reg\n                                              2. Показывается pop-up, уведомляющий о том, что username уже\n                                              используется\n                                              3. Пользователь с указанными данными не создается в БД\n        ", "attachments": [{"name": "log", "source": "d4bc788c-2810-419e-ac52-225d7b8a243b-attachment.txt", "type": "text/plain"}], "start": 1653175457216, "stop": 1653175457216, "uuid": "d7a7dd59-9883-471c-9dc4-e283846fc486", "historyId": "b9c21ee6a5db0c6af2a2dcbff7dce741", "testCaseId": "98df6fdeaaa3fc2cfb6c58987517d852", "fullName": "code.ui_myapp.tests.test_ui.TestUIUnauthorizedUserRegistrationPage#test_reg_page_validation_already_used_user", "labels": [{"name": "tag", "value": "UI"}, {"name": "parentSuite", "value": "code.ui_myapp.tests"}, {"name": "suite", "value": "test_ui"}, {"name": "subSuite", "value": "TestUIUnauthorizedUserRegistrationPage"}, {"name": "host", "value": "ebf8aaa79544"}, {"name": "thread", "value": "1-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "code.ui_myapp.tests.test_ui"}]}