{"name": "Проверка создания пользователя по username, длина которого больше допустимого (> 16 символов)", "status": "failed", "statusDetails": {"message": "AssertionError: Код ответа приложения должен быть 400\nassert 500 == 400\n  +500\n  -400", "trace": "self = <test_api.TestApiAuthorizedUser object at 0x7fccfaa2e0a0>\ncreate_user_data_with_middle_name = {'email': 'Ufl64ULbEuK@gmail.com', 'middle_name': 'CarolynHernandez', 'name': 'Carolyn', 'password': 'Z5M2RDpX99l54Z', ...}\n\n    @allure.title(\"Проверка создания пользователя по username, длина которого больше допустимого (> 16 символов)\")\n    @pytest.mark.API\n    def test_post_create_user_invalid_data_username_length_more_than_acceptable_bug(self,\n                                                                                    create_user_data_with_middle_name):\n        \"\"\"\n         Тестирование: Добавление пользователя с неккоректными данными\n         Эндпоинт: POST http://127.0.0.1:8086/api/user\n         Предусловия: Авторизация, создание пользовательских данных, заменить username на слово, длиной больше\n         допустимого (больше чем 16 символов)\n         Шаги:\n         1. Отправка запроса по API\n         Ожидаемый результат:\n         Код ответа - 400 (\"BAD REQUEST\") (-)\n         Пользователь НЕ добавляется в БД (+)\n         Фактический результат:\n         Код ответа - 500 (\"INTERNAL SERVER ERROR\")\n         Пользователь НЕ добавляется в БД\n         \"\"\"\n        complex_user_data = create_user_data_with_middle_name\n        complex_user_data[\"username\"] = RandomGenerate.generate_random_user_name(17, 70)\n    \n        response = self.post_create_user(complex_user_data)\n        self.mysql.session.commit()\n        user_db = self.mysql.session.query(Users).filter_by(email=complex_user_data['email']).first()\n    \n>       assert response.status_code == 400, \"Код ответа приложения должен быть 400\"\nE       AssertionError: Код ответа приложения должен быть 400\nE       assert 500 == 400\nE         +500\nE         -400\n\ncomplex_user_data = {'email': 'Ufl64ULbEuK@gmail.com', 'middle_name': 'CarolynHernandez', 'name': 'Carolyn', 'password': 'Z5M2RDpX99l54Z', ...}\ncreate_user_data_with_middle_name = {'email': 'Ufl64ULbEuK@gmail.com', 'middle_name': 'CarolynHernandez', 'name': 'Carolyn', 'password': 'Z5M2RDpX99l54Z', ...}\nresponse   = <Response [500]>\nself       = <test_api.TestApiAuthorizedUser object at 0x7fccfaa2e0a0>\nuser_db    = None\n\ncode/api_myapp/test/test_api.py:400: AssertionError"}, "description": "\n         Тестирование: Добавление пользователя с неккоректными данными\n         Эндпоинт: POST http://127.0.0.1:8086/api/user\n         Предусловия: Авторизация, создание пользовательских данных, заменить username на слово, длиной больше\n         допустимого (больше чем 16 символов)\n         Шаги:\n         1. Отправка запроса по API\n         Ожидаемый результат:\n         Код ответа - 400 (\"BAD REQUEST\") (-)\n         Пользователь НЕ добавляется в БД (+)\n         Фактический результат:\n         Код ответа - 500 (\"INTERNAL SERVER ERROR\")\n         Пользователь НЕ добавляется в БД\n         ", "steps": [{"name": "Выполняем POST запрос '/api/user'", "status": "passed", "steps": [{"name": "Выполняем запрос", "status": "passed", "parameters": [{"name": "method", "value": "'POST'"}, {"name": "location", "value": "'/api/user'"}, {"name": "headers", "value": "{'Content-Type': 'application/json'}"}, {"name": "data", "value": "None"}, {"name": "params", "value": "None"}, {"name": "json", "value": "{'username': 'VCwb0Ffmr8NEfdypNpeLv9YyUrLWTlaX7cpiUJbicCPkzL', 'password': 'Z5M2RDpX99l54Z', 'email': 'Ufl64ULbEuK@gmail.com', 'name': 'Carolyn', 'surname': 'Hernandez', 'middle_name': 'CarolynHernandez'}"}], "start": 1653225581777, "stop": 1653225581791}], "parameters": [{"name": "complex_data", "value": "{'username': 'VCwb0Ffmr8NEfdypNpeLv9YyUrLWTlaX7cpiUJbicCPkzL', 'password': 'Z5M2RDpX99l54Z', 'email': 'Ufl64ULbEuK@gmail.com', 'name': 'Carolyn', 'surname': 'Hernandez', 'middle_name': 'CarolynHernandez'}"}], "start": 1653225581777, "stop": 1653225581791}], "start": 1653225581776, "stop": 1653225581798, "uuid": "a8482b71-6fb7-420e-b0a7-a3d651ce921b", "historyId": "01c9646c660ece4170cd17732453e54d", "testCaseId": "c4c7638572c2db4d5b6a7e5e38d14966", "fullName": "code.api_myapp.test.test_api.TestApiAuthorizedUser#test_post_create_user_invalid_data_username_length_more_than_acceptable_bug", "labels": [{"name": "tag", "value": "API"}, {"name": "parentSuite", "value": "code.api_myapp.test"}, {"name": "suite", "value": "test_api"}, {"name": "subSuite", "value": "TestApiAuthorizedUser"}, {"name": "host", "value": "70606d8decda"}, {"name": "thread", "value": "1-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "code.api_myapp.test.test_api"}]}